// Generated by Wrangler on Tue Aug 13 2024 16:18:51 GMT+0700 (Western Indonesia Time)
// by running `wrangler types`

interface Env {
	puskesmas_tamblong_kv: KVNamespace;
	JWT_SECRET: "secretsecret";
	DB: D1Database;
}
